version: '2'
services:
    ccfusersapplication-app:
        image: ccfusersapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ccfusersapplication-mysql:3306/ccfusersapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ccfusersapplication-mysql:
        extends:
            file: mysql.yml
            service: ccfusersapplication-mysql
